### PR TITLE
StoryMap and ExB Support

### PR DESCRIPTION
**Pull request by dbouwman**
Adds support for StoryMap (full coverage) and ExB with limitations

ExB limitations
- does not handle image resources, as they store them in deep nested paths `/images/widget_12/some-image.png`
- limited/no test coverage

Also:
- extracts more resource helpers into separate files, with original and spy based tests
- adds type-specific logic into the `storeItemResources` - needed because some StoryMaps and ExB's have some json resources that need to be interpolated. Thus the type specific processor handles them.
- for ExB's we skip attempting to handle their deeply nested images at this time

### CODE REVIEW

**Comment by MikeTschudi** [comment]
[Travis CI passed](https://travis-ci.org/github/Esri/solution.js/builds/696075691)

**Comment by dbouwman** [comment]
Thanks @MikeTschudi

**Comment by dbouwman** [comment]
@MikeTschudi - cool - I was planning to add the test coverage in my next PR, but wanted to land this sooner vs later b/c it's getting kinda big. But I can fix up the ExB stuff today in this PR

**Comment by MikeTschudi** [comment]
@dbouwman, good point:  let's go with what's here, please

**Pull request merged**
